name = "nautica"
main = "_worker.js"
compatibility_date = "2023-08-23"
[[routes]]
pattern = "nautica.rachdik.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.nautica.rachdik.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.nautica.rachdik.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.nautica.rachdik.my.id"
custom_domain = true
[[routes]]
pattern = "zoomgov.nautica.rachdik.my.id"
custom_domain = true

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
